# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  vvj-simpledomain-api:
    image: simple-domain/api:latest
    build:
      context: ../
      dockerfile: src/VVJ.SimpleDomain.Api/Dockerfile
    ports:
      - 80
